### ISSUE TITLE
Adding social channels & forums to the site

### ISSUE THREAD

**Issue by kingo55** [grocy/grocy-website#1]
I think Grocy is a great idea and want to see how other people are using it and benefiting from it. Perhaps it could help new users get support without overwhelming Github issues too.

I suggest we set up a subreddit / Twitter and perhaps some other areas (e.g. Telegram or some chat area) for people to connect through.

Happy to set them up - the subreddit is still available - just don't want to be the owner while @berrnd may wish to manage this.

**Comment by berrnd** [comment]
Great idea, just don't know if there are that many users already - I don't have real numbers, just the website/demo visits (which vary between 50 - 150 daily unique visitors)...

Another thing would be documentation in general, but I currently don't have enough time to manage/create this all - the most discussion about grocy was on [/r/selfhosted](https://www.reddit.com/r/selfhosted/search?q=grocy&restrict_sr=1) in the past...

So feel free to setup a own subreddit, you can add [me](https://www.reddit.com/user/berrnd), but it's not necessary...

Thanks for your time and help. :)

**Comment by kingo55** [comment]
You're welcome - thanks for sharing the project...

I've registered the subreddit and invited you with full permissions. Will have to setup the stylesheet and get links added to the site next:

https://www.reddit.com/r/grocy/

**Comment by berrnd** [comment]
I've moved the hint on the website more to the top and also added a link in the [main projects README](https://github.com/grocy/grocy#getting-in-touch).

Additionally, I've registered a [Twitter account](https://twitter.com/grocy_erp) - posting new releases and stuff in the future there...

Thanks again for the great idea! :)

**Comment by kingo55** [comment]
Great... just added Twitter to the Reddit links list. 

Would be interesting to split test the position of the links. The [serial position effect](https://lawsofux.com/serial-position-effect.html) means the bottom of the page can work surprisingly well, too.
