### ISSUE TITLE
Promote the "Top grocy Add-ons / Helpers"

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy-website#15]
Let's switch the light grey area where currently only grocy-desktop is promoted to a [carousel](https://getbootstrap.com/docs/4.1/components/carousel/) and promote there the "Top grocy Add-ons / Helpers":

- grocy-desktop
- https://github.com/patzly/grocy-android
- PantryParty
- Barcode Buddy
- Hass.io Add-on

**Comment by berrnd** [comment]
That's now finally done. :)

/CC
@patzly, @arjes, @Forceu, @frenck

If anything should be described differently or other screenshots should be used, feel free to change it directly by a pull request here.

And thank you all a lot for constantly improving your tools! :)

**Comment by bmalinconico** [comment]
Thanks for the callout. I wish I could be more involved right now but baby and moving is killing my free time.

**Comment by berrnd** [comment]
Absolutely no problem and no excuses needed - grocy is currently and since a couple of months also a bit paused because a lot of other things are going on in my life right now ... but will hopefully change again soon ... and no promises from my side as always ... but I will do my best to make the christmas present [mentioned here](https://www.reddit.com/r/grocy/comments/hxeg31/when_can_we_expect_an_update/) reality... :D

**Comment by frenck** [comment]
Only comment I would have: Hass.io doesn't exists anymore (the term has been removed months ago). It is just Home Assistant now.

**Comment by berrnd** [comment]
> Hass.io doesn't exists anymore (the term has been removed months ago). It is just Home Assistant now.

Thanks, I just changed that...
