### ISSUE TITLE
Allow localizing the website

### ISSUE THREAD

**Issue by yarons** [grocy/grocy-website#19]
As far as I can understand the website is only available in English and German, since there is already a translators community why not translating the website as well?

**Comment by berrnd** [comment]
I've moved this issue to the correct repository.

It's a lot of "marketing like" text, if I look at some languages of the grocy project, I don't think this will be really good maintained over time. So no, let's keep this English (and German, just because that's my native language).

**Comment by yarons** [comment]
There are many projects that allow translating marketing text (Weblate, LibreOffice, VLC, etc.) and you can choose to include only languages with 90% completion and above so it won't look funny.
