### ISSUE TITLE
Pantry party not V3 ready

### ISSUE THREAD

**Issue by Festeazy** [grocy/grocy-website#24]
I would suggest either make a note or remove as add-on

https://github.com/PantryParty/pantry_party/issues/106

**Comment by berrnd** [comment]
There are so much things out there (the homepage lists 12) which use grocy and/or its API ... I can't care about which integration/add-on is compatible with which version all the time.

When it's about the API, there is the endpoint [`/system/info`](https://demo.grocy.info/api/system/info) to get the running version - preventing a connection with unsupported server versions is probably the best approach.

**Comment by arjes** [comment]
I agree I should add some checks, unfortunately life is kicking my ass right now :D
