### ISSUE TITLE
Add supergeorg/Grocy-SwiftUI to the top carousel

### ISSUE THREAD

**Issue by berrnd** [grocy/grocy-website#25]
https://www.reddit.com/r/grocy/comments/nhw962

https://github.com/supergeorg/Grocy-SwiftUI

**Comment by berrnd** [comment]
That's now done.

=> https://grocy.info

![grafik](https://user-images.githubusercontent.com/2161815/126030285-40cc9a4c-a32f-4d2d-b26d-bcfadb2dd399.png)

//CC @supergeorg

If anything should be described differently or other screenshots should be used, feel free to change it directly by a pull request here.

**Comment by supergeorg** [comment]
That you for this! It is really nice to be shown on the homepage.
