### ISSUE TITLE
Another python client, for data management only.

### ISSUE THREAD

**Issue by BlueBlueBlob** [grocy/grocy-website#8]
Hi :)

I'm cooking python client to manage entities like https://demo.grocy.info/api#/Generic%20entity%20interactions

For now add, edit, delete and list functions are available for products and chores. More incoming.

https://github.com/BlueBlueBlob/pygrocydm

Enjoy 👍 and thanks.

Kind regards

**Comment by BlueBlueBlob** [comment]
Update : only meal and recipe related entities are missing.
Functions : add, edit, delete, search, list.

Object userfields (get and edit) will come soon.

Btw, where can I contribute to API documentation.
Because a lot of entities are missing.

Keep in touch and best regards 👍

**Comment by berrnd** [comment]
The Swagger UI on `/api` is populated by a manually maintened OpenAPI 3.0 JSON file, this one: https://github.com/grocy/grocy/blob/master/grocy.openapi.json

**Comment by BlueBlueBlob** [comment]
> The Swagger UI on `/api` is populated by a manually maintened OpenAPI 3.0 JSON file, this one: https://github.com/grocy/grocy/blob/master/grocy.openapi.json

Well... I'm not a fan of copy/paste.
I'm thinking about a python script to update it. Will you be interested ?

Best regards

**Comment by berrnd** [comment]
If you mean to auto-generate the entities for `grocy.openapi.json` based on the database schema: Would only work for endpoints which return database rows "one to one", that's not the case for all API endpoints...

**Comment by BlueBlueBlob** [comment]
I was thinking about the generic part.
But it sounds like it's not a good idea ;)

Thank you again for your work 👍
